{% set name = "fps-kernel-subprocess" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_kernel_subprocess-{{ version }}.tar.gz
  sha256: 5228f87db30e98a2b4a57ba16cf615e4b0bb662d5322786e13eb6757db4e2853

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.12.0,<0.13.0
    - anyio
    - pyzmq
    - zmq-anyio >=0.3.1,<0.4.0

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - fps_kernel_subprocess

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/kernel_subprocess
  summary: An FPS plugin for the kernel subprocess API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/kernel_subprocess
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
