schema_version: 1

context:
  version: "0.1.9"

package:
  name: fps-kernel-subprocess
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/f/fps-kernel-subprocess/fps_kernel_subprocess-${{ version }}.tar.gz
    sha256: cfd2129b0abea1bdbd0cdb4c9d6fa2438ef98220c2a669554cd357353efef4ed

build:
  noarch: python
  number: 0
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - jupyverse-api >=0.14.0,<0.15.0
    - zmq-anyio >=0.3.1,<0.4.0

tests:
  - python:
      imports: fps_kernel_subprocess
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: COPYING.md
  homepage: https://github.com/jupyter-server/jupyverse/tree/main/plugins/kernel_subprocess
  summary: An FPS plugin for the kernel subprocess API

extra:
  recipe-maintainers:
    - davidbrochart
